package cc14.Databases;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Objects;

import cc14.UI.FlightTime;
import cc14.models.Booking;
import cc14.models.Flight;
import cc14.models.Passenger;

public class BookingDatabase {
    // TODO: add status (e.g., active, canceled)
    private static enum BookingStatus {
        ACTIVE,
        PROCESSING,
        CANCELED
    }

    // TODO: make this SQL based
    public static int CreateBooking(Passenger p, Flight f, String timestamp) {
        Booking booked_flight = new Booking(p, f, timestamp);

        // get passenger ID by username
        int passenger_id = getPassengerID(booked_flight.getPassenger());

        // get flight ID by flight number
        int flight_id = getFlightID(booked_flight.getFlight());
        try {
            Connection Database = DB_connection.connect();

            String sql = "INSERT INTO bookings_table (User_ID, flight_ID, status) VALUES (?, ?, ?)";

            PreparedStatement pstmt = Database.prepareStatement(sql);
            pstmt.setInt(1, passenger_id);
            pstmt.setInt(2, flight_id);

            // removed timestamp because it is auto-generated by mysql
            // pstmt.setString(3, timestamp);

            pstmt.setString(3, BookingStatus.ACTIVE.name());
            pstmt.executeUpdate();

            System.out.println("Booking added successfully.");
            return 1; // success

        } catch (SQLException e) {
            System.out.println("Error adding booking: " + e.getMessage());
        }

        return -1; // failure
    }

    public static ArrayList<Booking> getBookingsFor(Passenger p) {
        ArrayList<Booking> list = new ArrayList<>();
        for (Booking b : bookings) {
            if (b.getPassenger() == p)
                list.add(b);
        }
        return list;
    }

    public static boolean cancelBooking(Passenger p, String flightNumber) {
    /* 
        
    */

        /*
        Booking target = null;
        for (Booking b : bookings) {
            if (b.getPassenger() == p &&
                    b.getFlight().getFlightNumber().equalsIgnoreCase(flightNumber)) {
                target = b;
                break;
            }
        }
            */
    }

    /*
     * if (target != null) {
     * target.getFlight().increaseAvailableSeat();
     * bookings.remove(target);
     * return true;
     * }
     * 
     * return false;
     * }
     * 
     * public static ArrayList<Booking> getAllBookings() {
     * return bookings;
     * } // conflict check
     * 
     * 
     * public static boolean hasConflict(Passenger p, Flight newFlight) {
     * ArrayList<Booking> existing = getBookingsFor(p);
     * 
     * long newDep = FlightTime.toMillis(newFlight.getDepartureTime());
     * long newArr = FlightTime.toMillis(newFlight.getArrivalTime());
     * 
     * for (Booking b : existing) {
     * Flight f = b.getFlight();
     * 
     * long dep = FlightTime.toMillis(f.getDepartureTime());
     * long arr = FlightTime.toMillis(f.getArrivalTime());
     * 
     * boolean overlap =
     * (newDep >= dep && newDep <= arr) ||
     * (newArr >= dep && newArr <= arr);
     * 
     * if (overlap)
     * return true;
     * }
     * 
     * return false;
     * }
     */

    public static int getPassengerID(Passenger p) {
        if (p == null)
            return -1;

        String sql = "SELECT User_ID FROM users_table WHERE username = ?";
        try {
            Connection Database = DB_connection.connect();

            PreparedStatement pstmt = Database.prepareStatement(sql);
            pstmt.setString(1, p.getUsername());
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                return rs.getInt("User_ID");
            }

        } catch (SQLException e) {
            System.out.println("Error retrieving passenger ID: " + e.getMessage());
        }

        return -1;

    }

    public static int getFlightID(Flight f) {

        if (f == null)
            return -1;

        String sql = "SELECT Flight_ID FROM Flights_table WHERE Flight_Number = ?";

        try {
            Connection Database = DB_connection.connect();
            PreparedStatement pstmt = Database.prepareStatement(sql);
            pstmt.setString(1, f.getFlightNumber());
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                return rs.getInt("Flight_ID");
            }

        } catch (SQLException e) {
            System.out.println("Error retrieving passenger ID: " + e.getMessage());
        }

        return -1;
    }
}
